### ISSUE TITLE
Unable to install, consistent error message.

### ISSUE THREAD

**Issue by Casteele72** [lotgd/installer#1]
I am consistently getting he following error message trying to use the installer (I have no idea which component is causing the error--not even a clue if it's the installer itself or one of the packages it is installing):

```
$ php daenerys-install.php install
Daenerys installer, version 0.5.3
Installation of daenerys
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/doctrine-cache-bundle is abandoned, you should avoid using it. No replacement was suggested.
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package symfony/inflector is abandoned, you should avoid using it. Use use `EnglishInflector` from the String component instead instead.
Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
67 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Symfony recipes are disabled: "symfony/flex" not found in the root composer.json

Admin account name [admin]: ***
Password [changeme]: ***
Email address for login [admin@example.com]: ***

In ArrayNode.php line 315:
                                                                                                                                                                          
  Unrecognized options "dir_name, namespace" under "doctrine_migrations". Available options are "all_or_nothing", "check_database_platform", "connection", "custom_templ  
  ate", "em", "factories", "migrations", "migrations_paths", "organize_migrations", "services", "storage".

```

**Comment by Casteele72** [comment]
Sorry, forgot to add my system info:

```
$uname -all
Linux earth 5.4.0-0.bpo.4-amd64 #1 SMP Debian 5.4.19-1~bpo10+1 (2020-03-09) x86_64 GNU/Linux

```

**Comment by Vassyli** [comment]
It looks like the installation fails on the last command (vendor/bin/console cache:clear) for reasons that would need some more investigation.  I'm wrapping up a 0.6.0 release anyway, which hopefully clears this issue.

Running throws a similar error, though. Weird.

**Comment by Vassyli** [comment]
Downgrading will fix this issue:

`composer require doctrine/doctrine-migrations-bundle ^2.1 doctrine/migrations ^2.3 --ignore-platform-reqs`

**Comment by Vassyli** [comment]
Logging in leads to a error 500. You'll either need to inquire yourself or wait for the push to 0.6, my apologies.

**Comment by Vassyli** [comment]
@Casteele72 For getting it just running, I recommend cloning lotgd/crate-html instead and running it from there.

**Comment by Vassyli** [comment]
@Casteele72 I've updated the installer. Using the newest commits in dev-master should allow to install a running version. I recommend to install daenerys with ` php daenerys-install.php install --installDefaultModules`, otherwise using a character will not be possible (as there is no default scene handler).
